"""
SIF classifier (blueprint Part 2.3 approach #3 -> "Sentence-Transformer /
embedding + classifier head", adapted to the local TF-IDF+SVD embedding
backbone -- see app/ml/embeddings.py for that design decision).

Trained on the team-authored synthetic gold set (data/gold/gold_set.csv,
generated by data/synthetic/generate_synthetic_data.py) using embedding
vectors concatenated with the deterministic rule-engine's normalized risk
components as features, predicting among {HIGH, MEDIUM, LOW, NON_SIF}.
REVIEW is never a training target -- it is an abstention decision applied
afterwards from confidence/agreement between this classifier and the rule
engine (see app/services/analysis_service.py), matching the blueprint's
"never delegate abstention thresholds to the model" principle (Part 5.4).
"""
from __future__ import annotations

from pathlib import Path

import joblib
import numpy as np
from sklearn.linear_model import LogisticRegression

from app.ml.embeddings import get_embedding_provider

ARTIFACT_DIR = Path(__file__).resolve().parent / "artifacts"
ARTIFACT_DIR.mkdir(parents=True, exist_ok=True)
_MODEL_PATH = ARTIFACT_DIR / "sif_classifier.joblib"

LABELS = ["NON_SIF", "LOW", "MEDIUM", "HIGH"]


def build_feature_vector(embedding: list[float], rule_components: dict[str, float]) -> np.ndarray:
    extra = np.array([
        rule_components.get("hazard_energy_component", 0.0),
        rule_components.get("worker_exposure_component", 0.0),
        rule_components.get("barrier_failure_component", 0.0),
        rule_components.get("activity_criticality_component", 0.0),
        rule_components.get("repeat_precursor_component", 0.0),
    ])
    return np.concatenate([np.array(embedding), extra])


class SifClassifier:
    def __init__(self):
        self.model: LogisticRegression | None = None

    def train(self, feature_matrix: np.ndarray, labels: list[str]) -> dict:
        # Strong L2 regularization (small C) is deliberate: with only ~100
        # training rows and ~25 features (20-dim embedding + 5 rule
        # components), an unregularized model overfits almost perfectly
        # (train accuracy near 1.0) and then disagrees erratically with the
        # rule engine on unseen reports. See README "Known limitations".
        self.model = LogisticRegression(max_iter=2000, class_weight="balanced", C=0.35)
        self.model.fit(feature_matrix, labels)
        joblib.dump(self.model, _MODEL_PATH)
        train_accuracy = float(self.model.score(feature_matrix, labels))
        return {"train_accuracy": train_accuracy, "classes": list(self.model.classes_)}

    def load(self) -> bool:
        if _MODEL_PATH.exists():
            self.model = joblib.load(_MODEL_PATH)
            return True
        return False

    def is_ready(self) -> bool:
        return self.model is not None

    def predict_proba(self, feature_vector: np.ndarray) -> dict[str, float]:
        if not self.is_ready():
            raise RuntimeError("SifClassifier not trained/loaded yet.")
        probs = self.model.predict_proba(feature_vector.reshape(1, -1))[0]
        return {cls: float(p) for cls, p in zip(self.model.classes_, probs)}


_classifier_singleton: SifClassifier | None = None


def get_classifier() -> SifClassifier:
    global _classifier_singleton
    if _classifier_singleton is None:
        _classifier_singleton = SifClassifier()
        _classifier_singleton.load()
    return _classifier_singleton


def reload_classifier() -> None:
    """Forces the next get_classifier() call to reload from disk. Used by the
    seed/training script right after a fresh joblib.dump() so the same
    process picks up the newly trained model."""
    global _classifier_singleton
    _classifier_singleton = None
